# Generated by Django 4.2.2 on 2023-06-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0008_alter_appetizer_price_alter_dessert_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appetizer',
            name='type',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dessert',
            name='type',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='type',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
