# Generated by Django 4.2.2 on 2023-06-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0009_appetizer_type_dessert_type_maincourse_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appetizer',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maincourse',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
