# Generated by Django 4.2.2 on 2023-06-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0010_alter_appetizer_type_alter_dessert_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appetizer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maincourse',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
